### ISSUE TITLE
Floating IPs being created when the kubeapi LB status is `provisioning_status: ERROR`

### ISSUE THREAD

**Issue by kopiczko** [kubernetes-sigs/cluster-api-provider-openstack#1159]
/kind bug

**What steps did you take and what happened:**

I was trying to create a cluster when LB were failing to provision. That resulted in creating many floating IPs because of failed association.

**What did you expect to happen:**

At the very minimum I'd like to see only a single floating IP created and reused in subsequent reconciliation loops. Possibly the reconciliation should be stopped when the controller detects the LB is in `provisioning_status: ERROR`.

**Anything else you would like to add:**

Example logs (with the IP replaced):

```
I0301 10:00:01.055839       1 loadbalancer.go:45] controller/openstackcluster "msg"="Reconciling load balancer" "cluster"="pawe1" "namespace"="org-multi-project" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "name"="k8s-clusterapi-cluster-org-multi-project-pawe1-kubeapi"
I0301 10:00:05.210516       1 floatingip.go:122] controller/openstackcluster "msg"="Associating floating IP" "cluster"="pawe1" "name"="pawe1-bn82x" "namespace"="org-multi-project" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" "id"="06f512ab-f9f8-42b2-b85f-d538ef66f9c2" "ip"="1.2.3.4"
I0301 10:00:05.211167       1 recorder.go:103] events "msg"="Normal"  "message"="Created floating IP 1.2.3.4 with id 06f512ab-f9f8-42b2-b85f-d538ef66f9c2" "object"={"kind":"OpenStackCluster","namespace":"org-multi-project","name":"pawe1-bn82x","uid":"9e8c2a7a-a76d-431c-8bd8-3c87247fd869","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha4","resourceVersion":"1211905"} "reason"="SuccessfulCreateFloatingIP"
I0301 10:00:05.333980       1 recorder.go:103] events "msg"="Warning"  "message"="Failed to associate floating IP 1.2.3.4 with port a7f74d49-c74a-486c-a920-9e81a23a8c95: Resource not found" "object"={"kind":"OpenStackCluster","namespace":"org-multi-project","name":"pawe1-bn82x","uid":"9e8c2a7a-a76d-431c-8bd8-3c87247fd869","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha4","resourceVersion":"1211905"} "reason"="FailedAssociateFloatingIP"
E0301 10:00:05.348381       1 controller.go:317] controller/openstackcluster "msg"="Reconciler error" "error"="failed to reconcile load balancer: Resource not found" "name"="pawe1-bn82x" "namespace"="org-multi-project" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster"
```

From the LB:

```
provider: amphora
provisioning_status: ERROR
```

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.5.2
- Cluster-API version: 1.1.2
- OpenStack version: 
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mdbooth** [comment]
Incidentally, I've fixed the same issue for the Bastion FIP in #1153 (please review!). In that case I ensured we stored the Bastion FIP in `Status.Bastion.FloatingIP` regardless of whether the Bastion had been created yet.

I think the solution here is the similar: we need to write lbFloatingIP to `Status.Network.APIServerLoadBalancer.IP` immediately it's created regardless of association.

The next question is why we got to this point in the reconciler if the LB isn't ready. ReconcileLoadBalancer checks that ProvisioningStatus is ACTIVE before proceeding. I wonder which resource wasn't found. The port? Is so, how do we have an ID for it if it doesn't exist? Was it deleted?

**Comment by kopiczko** [comment]
> I wonder which resource wasn't found. The port? Is so, how do we have an ID for it if it doesn't exist? Was it deleted?

`a7f74d49-c74a-486c-a920-9e81a23a8c95` in logs is the Port ID of the LB. Apparently doesn't exist but you can still get the ID as a property of the LB which was failed to provision. That's probably a pretty corner case but it's polluting the OS with floating IP when it happens which is far from ideal.

**Comment by seanschneeweiss** [comment]
This seems to be a duplicate of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1114 and was fixed by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1115.

**Comment by kopiczko** [comment]
Thanks @seanschneeweiss. It isn't released though, is it?

**Comment by seanschneeweiss** [comment]
Sorry for my late response.
The fix was back ported such that the v0.5.3 release contains it.
v0.5.3 will be released soon.
